version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3001:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - api
    restart: unless-stopped
